# Generated by Django 4.0.3 on 2022-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carro_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aresta_n', models.IntegerField()),
                ('v_origem', models.IntegerField()),
                ('Loc_v_origem_x', models.IntegerField()),
                ('Loc_v_origem_y', models.IntegerField()),
                ('v_destino', models.IntegerField()),
                ('Loc_v_destino_x', models.IntegerField()),
                ('Loc_v_destino_y', models.IntegerField()),
                ('Distância_km', models.IntegerField()),
                ('Velocidade_km_h', models.IntegerField()),
            ],
        ),
    ]
