# Generated by Django 4.0.3 on 2022-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_grafo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField()),
                ('loc_cliente_x', models.FloatField()),
                ('loc_cliente_y', models.FloatField()),
                ('dest_cliente_x', models.FloatField()),
                ('dest_cliente_y', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='Aresta_n',
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='Distância_km',
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='Loc_v_destino_x',
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='Loc_v_destino_y',
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='Loc_v_origem_x',
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='Loc_v_origem_y',
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='Velocidade_km_h',
        ),
        migrations.AddField(
            model_name='grafo',
            name='aresta_n',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grafo',
            name='distancia_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grafo',
            name='loc_v_destino_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grafo',
            name='loc_v_destino_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grafo',
            name='loc_v_origem_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grafo',
            name='loc_v_origem_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grafo',
            name='velocidade_km_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='loc_carro_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carro',
            name='loc_carro_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grafo',
            name='v_destino',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grafo',
            name='v_origem',
            field=models.IntegerField(default=0),
        ),
    ]
